# Generated by Django 5.1 on 2024-08-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Course_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
    ]
