# Generated by Django 5.1 on 2024-08-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_outcomes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='pre_requisites',
            field=models.TextField(blank=True, null=True),
        ),
    ]
